version: '2'

services:
  mysqldb:
    image: docker.io/mysql:5.7
    container_name: mysqldb
    command: --max_allowed_packet=32505856
    volumes:
      - /home/raremon/Documents/Database/localmysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    privileged: true
    restart: always
    ports:
      - 3306:3306

networks:
 default:
  external:
   name: dockerfiles_tools_docknet
