version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ~/Documents/applicationData/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    container_name: localadminer
    restart: always
    ports:
      - 8080:8080

networks:
 default:
  external:
   name: dockerfiles_tools_docknet
